const baseCapabilities = {
  clientes: true,
  activos: true,
  ot: true,
  stock: true,
  appCampo: true,
  tesoreria: true,
  alquileres: false,
  flotaCliente: true,
  medidorUso: true,
}

export const rubrosTaxonomia = {
  maquinaria: {
    rubroLabel: 'Maquinaria',
    activoSingular: 'Activo',
    activoPlural: 'Activos',
    activoAsociado: 'Activo asociado',
    flotaCliente: 'Activos del cliente',
    medidor: 'Horómetro',
    medidorUnidad: 'hs',
    moduloTaller: 'Taller',
    ordenTrabajo: 'Orden de trabajo',
    ordenTrabajoPlural: 'Órdenes de trabajo',
    tecnico: 'Técnico',
    servicioCampo: 'Servicio a campo',
    repuesto: 'Repuesto',
    repuestoPlural: 'Repuestos',
    tiposActivo: [
      'excavadora',
      'minicargadora',
      'retroexcavadora',
      'cargadora',
      'topadora',
      'motoniveladora',
      'autoelevador',
      'camión',
      'camioneta',
      'grupo electrógeno',
      'compresor',
      'implemento',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
      alquileres: true,
    },
  },

  flota: {
    rubroLabel: 'Flota',
    activoSingular: 'Vehículo',
    activoPlural: 'Vehículos',
    activoAsociado: 'Vehículo asociado',
    flotaCliente: 'Flota del cliente',
    medidor: 'Kilometraje',
    medidorUnidad: 'km',
    moduloTaller: 'Taller',
    ordenTrabajo: 'Orden de trabajo',
    ordenTrabajoPlural: 'Órdenes de trabajo',
    tecnico: 'Técnico',
    servicioCampo: 'Asistencia en ruta / campo',
    repuesto: 'Repuesto',
    repuestoPlural: 'Repuestos',
    tiposActivo: [
      'auto',
      'camioneta',
      'camión',
      'utilitario',
      'semirremolque',
      'acoplado',
      'moto',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
    },
  },

  talleres: {
    rubroLabel: 'Taller',
    activoSingular: 'Activo',
    activoPlural: 'Activos',
    activoAsociado: 'Activo intervenido',
    flotaCliente: 'Activos del cliente',
    medidor: 'Uso',
    medidorUnidad: 'km/hs',
    moduloTaller: 'Taller',
    ordenTrabajo: 'Orden de reparación',
    ordenTrabajoPlural: 'Órdenes de reparación',
    tecnico: 'Mecánico',
    servicioCampo: 'Servicio externo',
    repuesto: 'Repuesto',
    repuestoPlural: 'Repuestos',
    tiposActivo: [
      'auto',
      'camioneta',
      'camión',
      'moto',
      'autoelevador',
      'zorra manual',
      'zorra eléctrica',
      'grupo electrógeno',
      'equipo técnico',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
      alquileres: false,
    },
  },

  rental: {
    rubroLabel: 'Rental',
    activoSingular: 'Activo',
    activoPlural: 'Activos',
    activoAsociado: 'Activo asociado',
    flotaCliente: 'Activos vinculados',
    medidor: 'Uso',
    medidorUnidad: 'hs',
    moduloTaller: 'Mantenimiento',
    ordenTrabajo: 'Orden de servicio',
    ordenTrabajoPlural: 'Órdenes de servicio',
    tecnico: 'Técnico',
    servicioCampo: 'Servicio a campo',
    repuesto: 'Repuesto',
    repuestoPlural: 'Repuestos',
    tiposActivo: [
      'maquinaria',
      'vehículo',
      'grupo electrógeno',
      'compresor',
      'autoelevador',
      'plataforma',
      'herramienta',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
      alquileres: true,
    },
  },

  agro: {
    rubroLabel: 'Agro',
    activoSingular: 'Activo',
    activoPlural: 'Activos',
    activoAsociado: 'Activo asociado',
    flotaCliente: 'Activos del cliente',
    medidor: 'Horómetro',
    medidorUnidad: 'hs',
    moduloTaller: 'Taller',
    ordenTrabajo: 'Orden de trabajo',
    ordenTrabajoPlural: 'Órdenes de trabajo',
    tecnico: 'Técnico',
    servicioCampo: 'Servicio en campo',
    repuesto: 'Repuesto',
    repuestoPlural: 'Repuestos',
    tiposActivo: [
      'tractor',
      'cosechadora',
      'pulverizadora',
      'sembradora',
      'implemento',
      'camioneta',
      'grupo electrógeno',
      'bomba',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
    },
  },

  mineria: {
    rubroLabel: 'Minería',
    activoSingular: 'Activo crítico',
    activoPlural: 'Activos críticos',
    activoAsociado: 'Activo crítico asociado',
    flotaCliente: 'Activos críticos del cliente',
    medidor: 'Horómetro',
    medidorUnidad: 'hs',
    moduloTaller: 'Taller',
    ordenTrabajo: 'Orden de intervención',
    ordenTrabajoPlural: 'Órdenes de intervención',
    tecnico: 'Técnico',
    servicioCampo: 'Intervención en sitio',
    repuesto: 'Repuesto crítico',
    repuestoPlural: 'Repuestos críticos',
    tiposActivo: [
      'equipo minero',
      'camión fuera de ruta',
      'cargadora',
      'excavadora',
      'grupo electrógeno',
      'bomba',
      'compresor',
      'planta',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
    },
  },

  logistica: {
    rubroLabel: 'Logística',
    activoSingular: 'Unidad',
    activoPlural: 'Unidades',
    activoAsociado: 'Unidad asociada',
    flotaCliente: 'Flota del cliente',
    medidor: 'Kilometraje',
    medidorUnidad: 'km',
    moduloTaller: 'Taller',
    ordenTrabajo: 'Orden de mantenimiento',
    ordenTrabajoPlural: 'Órdenes de mantenimiento',
    tecnico: 'Técnico',
    servicioCampo: 'Asistencia operativa',
    repuesto: 'Repuesto',
    repuestoPlural: 'Repuestos',
    tiposActivo: [
      'camión',
      'camioneta',
      'utilitario',
      'semirremolque',
      'acoplado',
      'zorra eléctrica',
      'autoelevador',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
    },
  },

  servicios_tecnicos: {
    rubroLabel: 'Servicios técnicos',
    activoSingular: 'Equipo',
    activoPlural: 'Equipos',
    activoAsociado: 'Equipo intervenido',
    flotaCliente: 'Equipos del cliente',
    medidor: 'Uso',
    medidorUnidad: 'ciclos',
    moduloTaller: 'Laboratorio',
    ordenTrabajo: 'Orden de servicio',
    ordenTrabajoPlural: 'Órdenes de servicio',
    tecnico: 'Técnico',
    servicioCampo: 'Visita técnica',
    repuesto: 'Insumo',
    repuestoPlural: 'Insumos',
    tiposActivo: [
      'equipo técnico',
      'equipo electrónico',
      'equipo médico',
      'equipo de laboratorio',
      'compresor',
      'bomba',
      'grupo electrógeno',
      'herramienta',
      'otro',
    ],
    capabilities: {
      ...baseCapabilities,
      stock: true,
    },
  },
}

export const RUBRO_DEFAULT = 'maquinaria'